apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waldur-postgresql
  namespace: argocd
spec:
  project: default
  source:
    path: applications/waldur-postgresql/manifests
    repoURL: https://github.com/waldur/csl-poc.git
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "waldur"
