apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  project: default
  sources:
  - chart: postgres-operator
    repoURL: https://opensource.zalando.com/postgres-operator/charts/
    targetRevision: 1.10.1
    helm:
      releaseName: postgres-operator
      valueFiles:
      - $override/applications/postgresql-operator/values-custom.yaml
  - repoURL: https://github.com/waldur/csl-poc.git
    targetRevision: HEAD
    ref: override
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "postgres-operator-system"
