ingress:
  tls:
    enabled: false

externalDB:
  enabled: true
  secretName: waldur.waldur-postgresql.credentials.postgresql.acid.zalan.do
  serviceName: waldur-postgresql

rabbitmq:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: false

global:
  imageRegistry: "registry.hpc.ut.ee/mirror"
