apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: waldur-postgresql
spec:
  teamId: "waldur"
  volume:
    size: 5Gi
  numberOfInstances: 2
  users:
    waldur:
    - superuser
    - createdb
  databases:
    waldur: waldur
  postgresql:
    version: "14"
  resources:
    requests:
      cpu: '500m'
      memory: 500Mi
    limits:
      cpu: '1'
      memory: 2Gi
