apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  sources:
  - chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.3.5
    helm:
      releaseName: rabbitmq
      valueFiles:
      - $override/applications/rabbitmq/values-custom.yaml
  - repoURL: https://github.com/waldur/csl-poc.git
    targetRevision: HEAD
    ref: override
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "waldur"
