apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
  - chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.4.4
    helm:
      releaseName: longhorn
      valueFiles:
      - $override/applications/longhorn/values-custom.yaml
  - repoURL: https://github.com/waldur/csl-poc.git
    targetRevision: HEAD
    ref: override
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "longhorn-system"
